version: '3'
services:
  
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: 'bitnami/kafka:2.8.1'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_NUM_PARTITIONS: 2
    ports:
      - 9092:9092

  api: 
    build: ./api
    restart: always
    environment:
      - kafkaHost=kafka:9092
    depends_on:
      - kafka
      - db
    ports:
      - 3000:3000

  stock: 
    build: ./stock
    restart: always
    environment:
      - kafkaHost=kafka:9092
    depends_on:
      - kafka
      - db
    ports:
      - 3001:3000

  ubicacion: 
    build: ./ubicacion
    restart: always
    environment:
      - kafkaHost=kafka:9092
    depends_on:
      - kafka
      - db
    ports:
      - 3002:3000
  
  venta: 
    build: ./venta
    restart: always
    environment:
      - kafkaHost=kafka:9092
    depends_on:
      - kafka
      - db
    ports:
      - 3003:3000

  db:
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example