version: '3'
services:
  
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: 'bitnami/kafka:2.8.1'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_NUM_PARTITIONS: 2
    ports:
      - 9092:9092

  api: 
    build: ./api
    restart: always
    environment:
      - kafkaHost=kafka:9092
    depends_on:
      - kafka
      - database
    ports:
      - 3000:3000

  stock: 
    build: ./stock
    restart: always
    environment:
      - kafkaHost=kafka:9092
    depends_on:
      - kafka
      - database
    ports:
      - 3001:3000

  ubicacion: 
    build: ./ubicacion
    restart: always
    environment:
      - kafkaHost=kafka:9092
    depends_on:
      - kafka
      - database
    ports:
      - 3002:3000
  
  venta: 
    build: ./venta
    restart: always
    environment:
      - kafkaHost=kafka:9092
    depends_on:
      - kafka
      - database
    ports:
      - 3003:3000
  
  # BASE DE DATOS 
  database:
    image: bitnami/postgresql:14.5.0
    container_name: database
    restart: always
    volumes:
       - './db/data:/bitnami/postgresql'
       - './db/data.sql:/docker-entrypoint-initdb.d/data.sql:ro'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - 5432:5432
    
    
    
    

